SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE,'%Y-%m-%d') AS OUT_DATE, 
IF(OUT_DATE IS NULL, '출고미정', 
   CASE WHEN OUT_DATE > '2022-05-01' THEN '출고대기' 
   ELSE '출고완료' END) AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC;
