SELECT FO.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = "2022" AND MONTH(PRODUCE_DATE) = "05"
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;