SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;