WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM # 초기값 설정
    UNION ALL
    SELECT NUM+1
    FROM CTE
    WHERE NUM < 23 # 반복을 멈추는 조건
)

SELECT CTE.NUM HOUR, IFNULL(AO.COUNT, 0) COUNT
FROM CTE
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
          FROM ANIMAL_OUTS
          GROUP BY HOUR(DATETIME)) AO
ON AO.HOUR = CTE.NUM
ORDER BY HOUR;


