SELECT HG.EMP_NO, EMP_NAME,
CASE WHEN AVG(SCORE) >= '96' THEN 'S'
    WHEN AVG(SCORE) >= '90' THEN 'A'
    WHEN AVG(SCORE) >= '80' THEN 'B'
    ELSE 'C' END GRADE,
CASE WHEN AVG(SCORE) >= '96' THEN ROUND(SAL*20/100,0)
    WHEN AVG(SCORE) >= '90' THEN ROUND(SAL*15/100,0)
    WHEN AVG(SCORE) >= '80' THEN ROUND(SAL*10/100,0)
    ELSE 0 END BONUS
FROM HR_EMPLOYEES HE
JOIN HR_DEPARTMENT HD
ON HE.DEPT_ID = HD.DEPT_ID
JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO;