SELECT HE.EMP_NO, EMP_NAME, 
    CASE WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C' END GRADE,
    CASE WHEN AVG(SCORE) >= 96 THEN SAL*0.2
        WHEN AVG(SCORE) >= 90 THEN SAL*0.15
        WHEN AVG(SCORE) >= 80 THEN SAL*0.1
        ELSE 0 END BONUS
FROM HR_EMPLOYEES HE
JOIN HR_DEPARTMENT HD
ON HE.DEPT_ID = HD.DEPT_ID
JOIN HR_GRADE HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY EMP_NO, YEAR
ORDER BY 1 ASC;