# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID
AND R.MEMBER_ID = (SELECT MEMBER_ID
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY COUNT(*) DESC
                LIMIT 1)
ORDER BY 3 ASC, 2 ASC;