SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_FILE UGF
ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE VIEWS = (SELECT VIEWS
              FROM USED_GOODS_BOARD UGB
              ORDER BY VIEWS DESC
              LIMIT 1)
ORDER BY FILE_ID DESC;